export enum PermissionCode {
  STAFF_MANAGE = 'STAFF_MANAGE',
  SETTINGS_READ = 'SETTINGS_READ',
  SETTINGS_WRITE = 'SETTINGS_WRITE',
  CATALOGUE_READ = 'CATALOGUE_READ',
  CATALOGUE_WRITE = 'CATALOGUE_WRITE',
  PRICING_READ = 'PRICING_READ',
  PRICING_WRITE = 'PRICING_WRITE',
  COMPANY_READ = 'COMPANY_READ',
  COMPANY_WRITE = 'COMPANY_WRITE',
  EMPLOYEE_READ = 'EMPLOYEE_READ',
  EMPLOYEE_WRITE = 'EMPLOYEE_WRITE',
  MENU_READ = 'MENU_READ',
  MENU_WRITE = 'MENU_WRITE',
  ORDER_READ = 'ORDER_READ',
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_EDIT = 'ORDER_EDIT',
  ORDER_OVERRIDE = 'ORDER_OVERRIDE',
  KITCHEN_READ = 'KITCHEN_READ',
  KITCHEN_UPDATE = 'KITCHEN_UPDATE',
  DISPATCH_READ = 'DISPATCH_READ',
  DISPATCH_UPDATE = 'DISPATCH_UPDATE',
  DELIVERY_OWN_READ = 'DELIVERY_OWN_READ',
  DELIVERY_OWN_UPDATE = 'DELIVERY_OWN_UPDATE',
  BILLING_READ = 'BILLING_READ',
  BILLING_WRITE = 'BILLING_WRITE',
}

export const permissionDescriptions: Record<PermissionCode, string> = {
  [PermissionCode.STAFF_MANAGE]: 'Manage internal staff users and roles.',
  [PermissionCode.SETTINGS_READ]: 'View platform settings.',
  [PermissionCode.SETTINGS_WRITE]: 'Change platform settings.',
  [PermissionCode.CATALOGUE_READ]: 'View catalogue data.',
  [PermissionCode.CATALOGUE_WRITE]: 'Manage catalogue data.',
  [PermissionCode.PRICING_READ]: 'View pricing data.',
  [PermissionCode.PRICING_WRITE]: 'Manage pricing data.',
  [PermissionCode.COMPANY_READ]: 'View company data.',
  [PermissionCode.COMPANY_WRITE]: 'Manage company data.',
  [PermissionCode.EMPLOYEE_READ]: 'View customer employee data.',
  [PermissionCode.EMPLOYEE_WRITE]: 'Manage customer employee data.',
  [PermissionCode.MENU_READ]: 'View menus.',
  [PermissionCode.MENU_WRITE]: 'Manage menus.',
  [PermissionCode.ORDER_READ]: 'View orders.',
  [PermissionCode.ORDER_CREATE]: 'Create orders.',
  [PermissionCode.ORDER_EDIT]: 'Edit orders before the cut-off.',
  [PermissionCode.ORDER_OVERRIDE]: 'Override order restrictions.',
  [PermissionCode.KITCHEN_READ]: 'View kitchen work.',
  [PermissionCode.KITCHEN_UPDATE]: 'Update kitchen work.',
  [PermissionCode.DISPATCH_READ]: 'View dispatch work.',
  [PermissionCode.DISPATCH_UPDATE]: 'Update dispatch work.',
  [PermissionCode.DELIVERY_OWN_READ]: 'View deliveries assigned to the current driver.',
  [PermissionCode.DELIVERY_OWN_UPDATE]: 'Update deliveries assigned to the current driver.',
  [PermissionCode.BILLING_READ]: 'View company billing.',
  [PermissionCode.BILLING_WRITE]: 'Manage company billing.',
};
